version: '3'

volumes:
  tmp: ~

services:
  github-runner:
    container_name: github-runner
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GITHUB_ORG: ${GITHUB_ORG}
    volumes:
      - tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
