
volumes:
  tmp: ~

services:
  github-runner:
    deploy:
      replicas: 1
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GITHUB_ORG: ${GITHUB_ORG}
      RUNNER_LABELS: ${RUNNER_LABELS}
      RUNNER_GROUP: ${RUNNER_GROUP}
    volumes:
      - tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
