version: '3'

services:
  github-runner:
    container_name: github-runner
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GITHUB_ORG: ${GITHUB_ORG}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
